print("--------------------Guest List--------------------")
invites = ["Connor", "Caitlyn", "Emmet"]
print(f"{invites[0]}, would you like to come to dinner?")
print(f"{invites[1]}, would you like to come to dinner?")
print(f"{invites[2]}, would you like to come to dinner?")
print("--------------------Changing Guest List--------------------")
print(f"{invites[2]} can't make it...")
invites.pop()
invites.append("Destiny")
print(f"{invites[0]}, would you like to come to dinner?")
print(f"{invites[1]}, would you like to come to dinner?")
print(f"{invites[2]}, would you like to come to dinner?")
print("--------------------More Guests--------------------")
print("Found a bigger dining table - bigger dining table means more guests!")
invites.insert(0, "Stephany")
invites.insert(2, "Grace")
invites.append("Dan")
print(f"{invites[0]}, would you like to come to dinner?")
print(f"{invites[1]}, would you like to come to dinner?")
print(f"{invites[2]}, would you like to come to dinner?")
print(f"{invites[3]}, would you like to come to dinner?")
print(f"{invites[4]}, would you like to come to dinner?")
print(f"{invites[5]}, would you like to come to dinner?")
print(f"I have invited {len(invites)} people to dinner.")
print("--------------------Shrinking Guest List--------------------")
print("The table won't arrive in time, only two guests can come for dinner...")
print(f"Sorry, {invites[-1]}, we can't have you for dinner...")
invites.pop()
print(f"Sorry, {invites[-1]}, we can't have you for dinner...")
invites.pop()
print(f"Sorry, {invites[-1]}, we can't have you for dinner...")
invites.pop()
print(f"Sorry, {invites[-1]}, we can't have you for dinner...")
invites.pop()
print(f"{invites[0]} and {invites[1]}, you can still come for dinner!")
del invites[0]
del invites[0]
print(invites)