print("-------------------------Lab 1-------------------------")
foods = ["steak", "onions", "ice cream", "chicken noodle soup", "mac & cheese", "calamari"]
print(f"Favorite Foods: {foods}")
numbers = [8, 15, 24, 30, 64, 100]
print(f"Favorite Numbers: {numbers}")
movies = ["Forrest Gump", "Jurassic Park", "Happy Feet"]
print(f"Favorite Movies: {movies}")
combo = [foods[0], foods[1], numbers[2], numbers[3], movies[0], movies[1]]
print(f"Two of Each: {combo}")
print(f"Last of Food List: {foods[-1]}")
print(f"2nd, 4th, and 6th numbers: {numbers[1]}, {numbers[3]}, {numbers[5]}")
print(f"All Movies: {movies[0]}, {movies[1]}, and {movies[2]}")
print(f"First Food, First Number, and First Movie from Combo List: {combo[0]}, {combo[2]}, {combo[4]}")
print("-------------------------Lab 2-------------------------")
movies.append("Legend of the Guardians")
print(f"Added Movie: {movies}")
numbers.insert(3, 47)
print(f"Added Number: {numbers}")
foods.insert(5, "ribs")
print(f"Added Food: {foods}")
del foods[1]
print(f"Deleted Food: {foods}")
numbers.pop()
print(f"Deleted Number: {numbers}")
numbers.pop(2)
print(f"Deleted Number: {numbers}")
print("-------------------------Lab 3-------------------------")
movies.sort()
print(f"Sorted Movies: {movies}")
foods.sort()
print(f"Sorted Foods: {foods}")
print(f"Temp Sorted Numbers: {sorted(numbers)}")
print(f"Unsorted Numbers: {numbers}")
movies.reverse()
print(f"Reverse Sorted Movies: {movies}")