print("==================5-1==================")
num = 5
print("Is num == 5? I predict True.")
print(num == 5)
print("Is num != 5? I predict False.")
print(num != 5)
print("Is num >= 7? I predict True.")
print(num >= 4)
print("Is num > 7? I predict False.")
print(num > 7)
print("Is num <= 7? I predict True.")
print(num <= 7)
print("Is num < 4? I predict False.")
print(num < 4)
print("Is num != 1? I predict True.")
print(num != 1)
print("Is num == 10? I predict False.")
print(num == 10)
print("==================5-2==================")
string = "cat"
print("Is string == 'cat'? I predict True.")
print(string == "cat")
print("Is string != 'cat? I predict False.")
print(string != "cat")
lower = "lower"
print("Is lower == LOWER.lower()? I predict True.")
print(lower == ("LOWER").lower())
upper = "UPPER"
print("Is UPPER == UPPER.lower()? I predict False.")
print(upper == ("UPPER").lower())
num1 = 5
num2 = 10
print("Is num1 == num2? I predict False.")
print(num1 == num2)
print("Is num1 != num2? I predict True.")
print(num1 != num2)
print("Is num1 >= num2? I predict False.")
print(num1 >= num2)
print("Is num1 > num2? I predict False.")
print(num > 7)
print("Is num1 <= num2? I predict True.")
print(num1 <= num2)
print("Is num2 < num2? I predict True.")
print(num1 < num2)
print("Is 1 > 3 and 5 < 7? I predict False.")
print(1 > 3 and 5 < 7)
print("Is 1 > 3 or 1 < 7? I predict True.")
print(1 > 3 or 1 < 7)
example = [1, 2, 3, 4]
print("Is 1 in the list? I predict True.")
print(1 in example)
print("Is 'dog' in the list? I predict False.")
print("dog" in example)
print("Is 'cat' not in the list? I predict True.")
print("cat" not in example)
print("Is 3 not in the list? I predict False.")
print(3 not in example)

